[package]
name = "model_storage"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
candid = "0.8"
ic-cdk = "0.11"
ic-cdk-macros = "0.6"
ic-stable-memory = "0.4"
serde = { version = "1.0", features = ["derive"] }


[dev-dependencies]
candid = "0.8"